def gv

pipeline {
    agent any
    tools {
      dockerTool 'Docker'
    }
    stages {
        stage("init groovy") {
            steps {
              script {
                gv = load "cicd/script.groovy"
              }
            }
        }
        stage("Cleanup") {
          steps {
            script {
                gv.cleanUp()
            }
          }
        }
        stage("Image Build") {
          when {
            expression {
              BRANCH_NAME == 'master'
            }
          }
            steps {
               script{
                gv.imageBuild()
               }
            }
        }
        stage("Image Test") {
          when {
            expression {
              BRANCH_NAME == 'master'
            }
          }
          steps {
            script {
                gv.imageTest()
            }
          }
        }
        stage("Image Push") {
          when {
            expression {
              BRANCH_NAME == 'master'
            }
          }
            steps {
               script{
                gv.imagePush()
               }
            }
        }
        stage("Deploy") {
            steps {
               script{
                gv.deploy()
               }
            }
        }
    }
    post {
        success {
            echo "======== Pipeline executed successfully ========"
        }
        failure {
            echo "======== Pipeline execution failed ========"
        }
    }
}
